sudo: required

language: node_js
node_js:
- "8.12.0"

addons: # get google-chrome-stable
  chrome: stable

before_install:
- rm -rf ~/.gnupg

install: # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
- wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/share/
- sudo chmod +x /usr/local/share/chromedriver
- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

before_script:
- export PLUGIN_DIR=$(pwd)
- ls -l
- sudo rm -rf /etc/mysql/
- sudo apt-get -qq purge mysql* graphviz*
- sudo apt-get -qq autoremove
- sudo apt-get update
- sudo bash -c 'echo -e "[user]\n\tname = abc\n\temail = root@localhost.com" > /home/travis/.gitconfig'
- sudo wget -qO ee rt.cx/ee && sudo bash ee
- source /etc/bash_completion.d/ee_auto.rc
- sudo ee -v
- sudo lsb_release  -a
- sudo ee site create wp.localtest.me --wpfc --user=ADMINUSER --email=easyengine@rtcamp.com --pass=ADMINPASS
- sudo sed -i '/^127.0.0.1/ s/$/ wp.localtest.me/' /etc/hosts
- sudo sed -i '/^127.0.0.1/ s/$/ localhost/' /etc/hosts
- sudo chmod 777 -R /var/www
- sudo nginx -t
- sudo service nginx reload
- cd /var/www/wp.localtest.me/htdocs/wp-content/plugins/ && ls
- wp --allow-root plugin deactivate w3-total-cache
- wp --allow-root plugin delete nginx-helper
- mkdir nginx-helper
- cd $PLUGIN_DIR
- cp -Rf * /var/www/wp.localtest.me/htdocs/wp-content/plugins/nginx-helper/
- cd /var/www/wp.localtest.me/htdocs/
- wp plugin activate --all
- cd $PLUGIN_DIR
- cd tests/functional/
- npm install -g nightwatch
- npm install
- npm i chromedriver --save

script:
- whereis google-chrome-stable
- whereis chromedriver
- nightwatch --verbose
